server:
  port: 64000

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: user-service-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/