server:
  port: 64100

spring:
  application:
    name: html-service

eureka:
  instance:
    instance-id: html-service-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/